### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by mkljczk** [alexanderepstein/cryptowatch#10]
Just in case you don't know, I have created snap package for Cryptowatch and it was (no idea how) the most popular package in November. Please, ignore the fact that I have created it in 1st of December… ;)

source: https://insights.ubuntu.com/2017/12/20/top-snaps-in-november/

**Comment by alexanderepstein** [comment]
I didn't know That! That's awesome I'm glad to see people like it, does the snap get updated whenever I upload a new version to pypi or does is it a manual process?

**Comment by mkljczk** [comment]
I have to manually update it, I'm going to do it more frequently. (I'm closing it, because in fact it's not an issue…)

**Comment by alexanderepstein** [comment]
Thats fine, I can throw you a message here anytime I update it just to keep you updated. How would one go about installing the snap package I would love to add this to the readme

**Comment by alexanderepstein** [comment]
I actually just saw the little snippet on how to install it on the website :confounded:

**Comment by alexanderepstein** [comment]
Updated cryptowatch to 0.0.9, the update added ripple and digibyte support

**Comment by alexanderepstein** [comment]
Updated cryptowatch to 0.0.9, the update added ripple and digibyte support
