### ISSUE TITLE
GLIBC_2.26 not found (required by python3)

### ISSUE THREAD

**Issue by MiguelTVG** [alexanderepstein/cryptowatch#12]
Hi, since yesterday, I thought it was an update, I can't start de application. I'm on ubuntu 16.04 LTS and this is the message:

python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by python3)

Nice app! Thanks for your work!

**Comment by alexanderepstein** [comment]
Huh I don't think that has anything to do with my project specifically. Can you run any python 3 application/script? 

And glad you like it!

**Comment by MiguelTVG** [comment]
Thanks for your answer Alex!

I'm not an expert but I thought that the good thing in the snap packages was to not have problems with the dependeces. Maybe the problem is not in your code is it more on the snap.

Your application was very useful for me, but now I can't use it :(

Thanks any way!

**Comment by alexanderepstein** [comment]
Ah I personally do not use snap packages so I'm not sure how that works although I understand their philosophy. Can you try doing a pip install instead of using the snap package?

**Comment by MiguelTVG** [comment]
With the pip install is working! :) :+1: 
Thank you very much for your help. And I apologize if this is not the right channel for this kind of cuestions.
Please keep doing this great work!

**Comment by alexanderepstein** [comment]
Awesome, glad to hear it!
No problem, this is not exactly the right place but thats only because this is not a problem I could directly fix, but its no big deal that you came here to ask I am just happy I was able to help 🎉
