### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by delirious-lettuce** [alexanderepstein/cryptowatch#3]
https://github.com/alexanderepstein/cryptowatch/blob/51c655fa9cc75b77140e304848f6767d6bf233c9/cryptoPie/cryptoPie.py#L107

```python
def main():
    screen.enable_display(True)  # just in case
    screen.clear()  # just in case
    screen.home()  # start at inital position
    while True:
        showCryptoStats("bitcoin")
        showCryptoStats("ethereum")
        showCryptoStats("litecoin")
    except KeyboardInterrupt:  # <-- where is the `try`?
        screen.clear()
        screen.enable_display(False)
```

You are missing the `try` in the `try/except`. I wasn't sure whether you intended to have the `while` loop inside of the `try/except` or if you just wanted the three `showCryptoStats` calls inside but either way, this doesn't work.

**Comment by alexanderepstein** [comment]
Oops bad miss I meant to encase the while loop inside the try, basically allowing the user to close the monitor and it would clear the screen and turn it off. Thanks for posting the issue I will fix this right now :+1:

**Comment by delirious-lettuce** [comment]
@alexanderepstein ,

Ah ok, no problem! I'm just reading through the code right now and I might make a PR or two in the next little while (but you can fix this one).

**Comment by alexanderepstein** [comment]
Fixed in commit 2e604e511e976bdb685503e6383b8c33c55a06db and that would be awesome!

**Comment by delirious-lettuce** [comment]
@alexanderepstein ,

Nice, you are very fast!

**Comment by alexanderepstein** [comment]
Thanks!
